# fly.toml app configuration file generated for sbrp on 2023-09-16T20:13:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sbrp"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
