export const GET_ROLE_LISTINGS = 'GET_ROLE_LISTINGS';
export const ROLE_LISTINGS_ERROR = 'ROLE_LISTINGS_ERROR';
export const SORT_ROLE_LISTINGS_BY_NAME = 'SORT_ROLE_LISTINGS_BY_NAME';
export const GET_ROLES = 'GET_ROLES';
export const ROLES_ERROR = 'ROLES_ERROR';
export const FILTER_ROLE_LISTINGS_BY_ROLE_ID = 'FILTER_ROLE_LISTINGS_BY_ROLE_ID';
export const SORT_ROLE_LISTINGS_BY_DATE = 'SORT_ROLE_LISTINGS_BY_DATE';
