export const GET_ROLE_LISTINGS = 'GET_ROLE_LISTINGS';
export const ROLE_LISTINGS_ERROR = 'ROLE_LISTINGS_ERROR';
export const SORT_ROLE_LISTINGS_BY_NAME = 'SORT_ROLE_LISTINGS_BY_NAME';
export const GET_STAFF_SKILLS = 'GET_STAFF_SKILLS';
export const STAFF_SKILLS_ERROR = 'STAFF_SKILLS_ERROR';